routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

Route::get('/home', 'AdminController@index')->name('home');
//Route::get('{id}/profile', 'Resource\DisputeUserResource@edit')->name('dispute-users.edit');
//Route::get('{id}/profile', 'Resource\DisputeUserResource@edit')->name('disputeuser.edit');

Route::resource('users', 'Resource\UserResource');
Route::resource('transporters', 'Resource\TransporterResource');
Route::resource('disputeuser', 'Resource\DisputeUserResource');
Route::post('users/addamount', 	'Resource\UserResource@addamount')->name('users.addamount');
	

Route::resource('categories', 'Resource\CategoryResource');
Route::resource('subcategories', 'Resource\SubCategoryResource');
Route::get('subcategory', 'Resource\CategoryResource@subcategory');
Route::resource('categories.products', 'Resource\ProductResource');
Route::resource('products', 'Resource\ProductResource');
Route::delete('productimage/{id}', 'Resource\ProductResource@imagedestroy')->name('productimage.destroy');
Route::resource('orders', 'Resource\OrderResource');
Route::resource('shops', 'Resource\ShopResource');
Route::resource('shoptypes', 'Resource\ShopTypeResource');
Route::resource('shoptypecommision', 'Resource\ShopTypeCommisionResource');
Route::resource('zones', 'Resource\ZoneResource');
Route::resource('cuisines', 'Resource\CuisineResource');
Route::resource('demoapp', 'ManageappController');
Route::resource('promocodes', 'Resource\PromocodeResource');
Route::resource('emailtemplate', 'Resource\EmailTemplateResource');
Route::resource('translation', 'Resource\TranslationResource');
Route::get('disputes/{name}', 'Resource\DisputeResource@index');
Route::resource('dispute', 'Resource\DisputeResource');
Route::resource('banner', 'Resource\ShopBannerResource');
Route::resource('notice', 'Resource\NoticeBoardResource');
Route::resource('disputehelp', 'Resource\DisputeHelpResource');
Route::get('/settings', 'AdminController@settings')->name('settings');;
Route::post('/settings', 'AdminController@settings_store')->name('settings.store');;
//Route::get('/accsetting', 'AdminController@account_setting')->name('accsetting');;
Route::post('/setting/add', 'AdminController@AccountSettingStore')->name('accsetting.store');;

Route::get('/send/push', 'AdminController@push')->name('push');
Route::post('/send/push', 'AdminController@send_push')->name('send.push');

Route::get('/chat','Resource\DisputeResource@chatWithUser');

Route::post('/pages', 'AdminController@pages')->name('pages.update');

//pages

Route::get('/privacy', 'AdminController@privacy')->name('privacy');
Route::get('/terms', 'AdminController@terms')->name('terms');
Route::get('/faq', 'AdminController@faq')->name('faq');
Route::get('/about', 'AdminController@about')->name('about');
Route::get('/help', 'AdminController@help')->name('help');
Route::get('/refund', 'AdminController@refund')->name('refund');
Route::get('/queries', 'AdminController@queries')->name('queries');
Route::get('/otherterms', 'AdminController@otherterms')->name('otherterms');
Route::get('/contact', 'AdminController@contact')->name('contact');

Route::get('/leadres', 'AdminController@restuarant_leads')->name('leadres');
Route::get('/newsletter', 'AdminController@newsletter_leads')->name('newsletter');
Route::get('/enquiry_delivery', 'AdminController@enquiry_delivery')->name('enquiry_delivery');


Route::resource('addons', 'Resource\AddonsResource');
Route::get('transporters-shift', 'Resource\TransporterResource@shiftdetails');

//bulk product

Route::get('product/bulk', 'Resource\ProductResource@product_bulk')->name('product.bulk');
Route::post('product/store_bulk', 'Resource\ProductResource@product_csv')->name('product.store_bulk');

routes/user.php
<?php

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/

Route::get('/home', 'UserController@index')->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
//abort(404, 'The resource you are looking for could not be found');
Route::get('/', 'WelcomeController@home');

// Route::get('initsetup', function () {
//     return Setting::all();
// });

Route::view('/privacy', 'static', ['page' => 'privacy' , 'title' => 'Privacy Policy' ]);

Route::view('/aboutus', 'static', ['page' => 'about' , 'title' => 'About Us' ]);

Route::view('/terms', 'static', ['page' => 'terms' , 'title' => 'Terms And Condition' ]);

Route::view('/contact', 'static', ['page' => 'contact' , 'title' => 'Contact Us' ]);

Route::view('/help', 'static', ['page' => 'help' , 'title' => 'Help' ]);

Route::view('/refund', 'static', ['page' => 'refund' , 'title' => 'Refund' ]);

Route::view('otherterms', 'static', ['page' => 'otherterms' , 'title' => 'Other Terms' ]);

Route::get('/molpay/view','PaymentController@molpay_view');

Route::any('/molpay/callback','PaymentController@molpay_callback');

Route::get('/search','WelcomeController@search');
Route::get('/enquiry-delivery','UserController@delivery');
Route::post('/enquiry-delivery','UserController@delivery_store');


Route::get('auth/facebook', 'SocialLoginController@redirectToFaceBook');
Route::get('auth/facebook/callback', 'SocialLoginController@handleFacebookCallback');
Route::get('auth/google', 'SocialLoginController@redirectToGoogle');

Route::get('auth/google/callback', 'SocialLoginController@handleGoogleCallback');

Route::get('check/push','SendPushNotification@check_push');

Route::post('/social/login','SocialLoginController@loginWithSocial');



Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminAuth\LoginController@showLoginForm');
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout');

    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'AdminAuth\RegisterController@register');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'shop'], function () {
    Route::get('/', 'ShopAuth\LoginController@showLoginForm');
    Route::get('/login', 'ShopAuth\LoginController@showLoginForm');
    Route::post('/login', 'ShopAuth\LoginController@login');
    Route::post('/logout', 'ShopAuth\LoginController@logout');

    Route::get('/register', 'ShopAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'ShopAuth\RegisterController@register');

    Route::post('/password/email', 'ShopAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'ShopAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'ShopAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'ShopAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'transporter'], function () {
    Route::get('/login', 'TransporterAuth\LoginController@showLoginForm');
    Route::post('/login', 'TransporterAuth\LoginController@login');
    Route::post('/userlogin', 'TransporterAuth\LoginController@UserLogin');
    Route::get('/otplogin', 'TransporterAuth\LoginController@OtpLogin');
    Route::post('/logout', 'TransporterAuth\LoginController@logout');

    Route::post('/otp', 'TransporterAuth\RegisterController@OTP');
    Route::post('/verifyotp', 'TransporterAuth\RegisterController@CheckOtp');

    Route::get('/register', 'TransporterAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'TransporterAuth\RegisterController@register');

    Route::post('/password/email', 'TransporterAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'TransporterAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'TransporterAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'TransporterAuth\ResetPasswordController@showResetForm');

    Route::get('/home', 'TransporterController@index');
});

    Auth::routes();
    Route::get('login',function(){
        return redirect('/');
    });
    Route::get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::get('register','Auth\RegisterController@showRegistrationForm');
    Route::get('/home', 'UserController@showhome');
    Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.request');
    Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/user/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

    Route::post('register', 'Auth\RegisterController@register')->name('register');
    Route::post('shopreg', 'ShopController@register')->name('shopregister');
    Route::post('newsletter', 'WelcomeController@newsletter')->name('newsletter');

    Route::post('/otp', 'Auth\RegisterController@OTP');
    Route::get('/dashboard', 'UserResource\OrderResource@orderprogress');
    Route::get('/profile', 'UserResource\ProfileController@index');
    Route::post('/profile', 'UserResource\ProfileController@update');
    Route::get('/changepassword', 'UserResource\ProfileController@changepassword');
    Route::post('/setpassword', 'UserResource\ProfileController@password');
    Route::resource('orders', 'UserResource\OrderResource');
    Route::resource('useraddress', 'UserResource\AddressResource');
    Route::post('/cancel/order', 'UserResource\OrderResource@cancelorder');
    Route::get('/restaurants', 'UserResource\SearchResource@index');
    Route::get('/restaurant/details', 'UserResource\SearchResource@show');
    Route::get('/restaurant/viewdetails', 'UserResource\SearchResource@viewdetails');
    Route::post('mycart', 'UserResource\CartResource@addToCart');
    Route::post('addcart', 'UserResource\CartResource@store');
    Route::get('/clear/cart','UserResource\CartResource@clearCart');
    Route::get('/track/order/{id}','UserResource\SearchResource@ordertrack');
    Route::get('/product/details/{productid}/{cartId}/{shopname}/{productname}','UserResource\SearchResource@productDetails');
    // card
    Route::resource('card', 'Resource\CardResource');
    Route::get('payment', 'UserController@payment');
    Route::post('payment/confirm', 'PaymentController@payment');
    Route::any('cart/payment', 'UserController@order_payment');
    Route::get('wallet', 'UserController@wallet');
    Route::post('wallet', 'PaymentController@add_money');
    Route::post('/rating', 'UserResource\OrderResource@rate_review');
    Route::get('user/chat', 'UserResource\OrderResource@chatWithUser');
    Route::get('addons/{id}', 'Resource\ProductResource@show');
    Route::get('checkRipplePayment','PaymentController@checkRipplePayment');
    Route::get('checkEtherPayment','PaymentController@checkEtherPayment');
    // swiggy design
    Route::get('payments', 'UserController@payment');
    Route::resource('favourite', 'Resource\FavoriteResource');
    Route::get('offers', 'UserResource\SearchResource@offers');
    Route::get('legal', 'UserResource\SearchResource@legal');
    Route::get('faq', 'UserResource\SearchResource@faq');
    Route::get('queries', 'UserResource\SearchResource@queries');
    Route::post('wallet/promocode', 'UserResource\WalletResource@store');
    Route::post('/reorder', 'UserResource\OrderResource@reorder');

    Route::post('/molpay/return', 'PaymentController@molpay_return');
    
    //Route::get('/token','BraintreeTokenController@token');
    //Route::get('/payment','BraintreeTokenController@payment');
   // Route::post('/payment','BraintreeTokenController@do_payment');
    // Route::get('faq','WelcomeController@faq');
    // Route::get('aboutus','WelcomeController@aboutus');
    // Route::get('termcondition','WelcomeController@termcondition');

    //updatecartResource
    Route::resource('updatecart', 'UserResource\UpdateCartResource');
    Route::resource('referral', 'UserResource\ReferralResource');

    Route::get('/restaurant/details/addcart/{name}', 'UserResource\SearchResource@cart_checkout');
    Route::get('/product/search','UserResource\SearchResource@product_search');

    Route::get('/related/product','UserResource\SearchResource@product_related');

    Route::get('/product/filter','UserResource\SearchResource@product_filter');

    Route::get('/product/imageDimension','UserResource\SearchResource@product_image_dimension');

   

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Category extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'parent_id',
        'shop_id',
        'position',
        'commision',
        'is_admin',
        'status',
        'shop_type_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at', 'deleted_at',
    ];
    //protected $with = ['subcategories'];

    /**
     * Category Images
     */
    public function images()
    {
        return $this->hasMany('App\CategoryImage');
    }

    /**
     * Category 
     */
    public function subcategories()
    {
        return $this->hasMany('App\Category', 'parent_id', 'id');
    }

    /**
     * Category 
     */
    public function categories()
    {
        return $this->hasMany('App\Category', 'id');
    }

    /**
     * SubCategory 
     */
    public function subcategory()
    {
        return $this->hasMany('App\SubCategory');
    }

    /**
     * Categories that the category belongs to.
     */
    public function categoryproducts()
    {
        return $this->hasMany('App\CategoryProduct');
    }

    /**
     * Products belonging to the category
     */
    public function products()
    {
        return $this->belongsToMany('App\Product')->where('status','enabled')->orderBy(\DB::raw('ISNULL(position), position'),'ASC');;
    }

    /**
     * Shoptype that the Categories belongs to.
     */
    public function shoptype()
    {
        return $this->belongsTo('App\ShopType','shop_type_id');
    }

    /**
     * Get the list of all categories along with subcategories and images.
     */
    public function scopeList($query, $shop_id = NULL,$user_id = NULL)
    {
        return $query->with(['products','products.prices','products.images','products.addons','products.cart' => function($query) use ($user_id){
                return $query->where('user_id', $user_id);
            },'products.cart.cart_addons','images'])->where('shop_id',$shop_id)->get();
    }

    public function scopeSearch($query, $shop_id = NULL,$user_id = NULL,$category_id= NULL, $prodname= NULL)
    {
        return $query->with(['products' => function($query) use ($prodname){ 
            return $query->where('name', 'LIKE', '%' . $prodname . '%');},'products.prices','products.images','products.addons','products.cart' => function($query) use ($user_id){
                return $query->where('user_id', $user_id);
            },'products.cart.cart_addons','images'])->where('shop_id',$shop_id)->where('id',$category_id)->get();
    }

    public function scopeFilterbybrand($query, $shop_id = NULL,$user_id = NULL,$category_id= NULL, $prodbrand= NULL)
    {
        return $query->with(['products' => function($query) use ($prodname){ 
            return $query->whereIn('brand',$prodname);},'products.prices','products.images','products.addons','products.cart' => function($query) use ($user_id){
                return $query->where('user_id', $user_id);
            },'products.cart.cart_addons','images'])
             ->where('shop_id',$shop_id)->where('id',$category_id)
            ->get();
    }

    /**
     * Get the list of all categories along with subcategories and images.
     */
    public function scopeListwithsubcategory($query, $shop_id = NULL,$user_id = NULL)
    {
        return $query->with(['subcategories.products','subcategories.products.prices','subcategories.products.images','subcategories.products.addons','subcategories.products.cart' => function($query) use ($user_id){
                return $query->where('user_id', $user_id);
            }])->where('shop_id',$shop_id)->get();
    }

    /**
     * Get the list of all products that belong to the category with prices and images.
     */
    public function scopeProductList($query, $shop_id = NULL)
    {
        return $query->where('shop_id',$shop_id)->with('products', 'products.images', 'products.prices', 'products.variants', 'products.variants.images', 'products.variants.prices','images');
    }

    public function scopeListwithshoptype($query)
    {
        return $query->with(['shoptype.name'])->get();
    }
}

resources/views/admin/categories/sub_category/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">@lang('inventory.category.addsub_title')</h3>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <form role="form" method="POST" action="{{ route('admin.subcategories.store') }}" enctype="multipart/form-data">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name">@lang('inventory.category.name')</label>

                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                    @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                    @endif
                </div>

                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                    <label for="description">@lang('inventory.category.desc')</label>

                    <textarea class="form-control" id="description" name="description" rows="3" required>{{ old('description') }}</textarea>

                    @if ($errors->has('description'))
                        <span class="help-block">
                            <strong>{{ $errors->first('description') }}</strong>
                        </span>
                    @endif
                </div>

                <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                    <label for="parent_id">@lang('inventory.category.category_name'): @if(Request::get('category')) {{\App\Category::find(Request::get('category'))->name}} @endif</label>
                    <input name="category_id" type="hidden" value="{{Request::get('category')}}" />
                    @if ($errors->has('category_id'))
                        <span class="help-block">
                            <strong>{{ $errors->first('category_id') }}</strong>
                        </span>
                    @endif
                </div>

                <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                    <label for="status">@lang('inventory.category.status')</label>

                    <select class="form-control" id="status" name="status">
                        <option value="enabled">Enabled</option>
                        <option value="disabled">Disabled</option>
                    </select>

                    @if ($errors->has('status'))
                        <span class="help-block">
                            <strong>{{ $errors->first('status') }}</strong>
                        </span>
                    @endif
                </div>

                <div class="col-xs-12 mb-2">
                    <a href="{{ route('admin.subcategories.index') }}?category={{$_GET['category']}}" class="btn btn-warning mr-1">
                        <i class="ft-x"></i> Cancel
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-check-square-o"></i> Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('styles')
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/multiselect/css/multi-select.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/dropify/dist/css/dropify.min.css') }}">
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('assets/admin/plugins/multiselect/js/jquery.multi-select.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/admin/plugins/dropify/dist/js/dropify.min.js') }}"></script>
<script type="text/javascript">
    //$('#categories').multiSelect({ selectableOptgroup: true });
    $('.dropify').dropify();
</script>
@endsection

resources/views/admin/categories/sub_category/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">@lang('inventory.category.editsub_title')</h3>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <form role="form" method="POST" action="{{ route('admin.subcategories.update', $SubCategory->id) }}" enctype="multipart/form-data">
                {{ method_field('PATCH') }}
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name">@lang('inventory.category.name')</label>

                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name', $SubCategory->name) }}" required autofocus>

                    @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                    @endif
                </div>

                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                    <label for="description">@lang('inventory.category.desc')</label>

                    <textarea class="form-control" id="description" name="description" rows="3" required>{{ old('description', $SubCategory->description) }}</textarea>

                    @if ($errors->has('description'))
                        <span class="help-block">
                            <strong>{{ $errors->first('description') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                    <label for="status">@lang('inventory.category.status')</label>

                    <select class="form-control" id="status" name="status">
                        <option value="enabled" @if($SubCategory->status == "enabled") selected @endif>Enabled</option>
                        <option value="disabled" @if($SubCategory->status == "disabled") selected @endif>Disabled</option>
                    </select>

                    @if ($errors->has('status'))
                        <span class="help-block">
                            <strong>{{ $errors->first('status') }}</strong>
                        </span>
                    @endif
                </div>

                 <div class="col-xs-12 mb-2">
                    <a href="{{ route('admin.subcategories.index') }}?category={{$_GET['category']}}" class="btn btn-warning mr-1">
                        <i class="ft-x"></i> Cancel
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-check-square-o"></i> Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('styles')
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/multiselect/css/multi-select.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/dropify/dist/css/dropify.min.css') }}">
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('assets/admin/plugins/multiselect/js/jquery.multi-select.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/admin/plugins/dropify/dist/js/dropify.min.js') }}"></script>
<script type="text/javascript">
    $('#categories').multiSelect({ selectableOptgroup: true });
    $('.dropify').dropify();
</script>
@endsection

resources/views/admin/categories/sub_category/index.blade.php
@extends('admin.layouts.app')

@section('content')

<!-- File export table -->
    <div class="row file">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    @if(Setting::get('DEMO_MODE')==0)
                        <div class="col-md-12" style="height:50px;color:red;">
                           ** Demo Mode : No Permission to Edit and Delete.
                        </div>
                    @endif
                    <h4 class="card-title">@lang('inventory.category.sub_title')</h4>
                    <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                        <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                        <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                        <li><a href="{{ route('admin.subcategories.create') }}?category={{Request::get('category')}}" class="btn btn-primary add-btn btn-darken-3">@lang('inventory.category.add_subcategory')</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-body collapse in">
                                <div class="card-block card-dashboard table-responsive">
                                    <table class="table table-striped table-bordered file-export">
                                        <thead>
                                            <tr>
                                                <th>@lang('inventory.category.sl_no')</th>
                                                <th>@lang('inventory.category.name')</th>
                                                <th>@lang('inventory.category.action')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @forelse($SubCategories as $key=>$SubCategory)
                                            <tr>
                                                <td>{{$key+1}}</td>
                                                <td>{{$SubCategory->name}}</td>
                                                <td>
                                                   
                                                    <a href="{{ route('admin.subcategories.edit', $SubCategory->id) }}?category={{Request::get('category')}}" class="table-btn btn btn-icon btn-success"><i class="fa fa-pencil-square-o"></i></a>
                                                    @if(Setting::get('DEMO_MODE') == "1")
                                                    <button  class="table-btn btn btn-icon btn-danger" form="resource-delete-{{ $SubCategory->id }}" ><i class="fa fa-trash-o"></i></button> 
                                                    @endif
                                                    <form id="resource-delete-{{ $SubCategory->id }}" action="{{ route('admin.subcategories.destroy', $SubCategory->id)}}" method="POST">

                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                    </form>
                                                </td>
                                            </tr>
                                            @empty
                                                <div class="row">
                                                    <div class="col-xs-12 text-center">
                                                        <h4>@lang('inventory.category.sub_no_record_found')</h4>
                                                    </div>
                                                </div>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- File export table -->
@endsection